title: Sunnywu's Blog
author: Chao Yuan
email: sunnywu614714@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog use to study how to building a web page on github、and study how to use github stay my notes!

# social links
twitter_username: sunnywu
github_username:  Love-LG

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
